# Generated by Django 4.2.16 on 2024-11-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_teg_tag_alter_recipe_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='ShoppingCart',
        ),
    ]
