# Generated by Django 4.2.16 on 2024-11-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_favorite_options_alter_shoppingcart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shoppingcarts', 'ordering': ('user',), 'verbose_name': 'список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
    ]
