# Generated by Django 4.2.16 on 2024-11-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Килограммы'), ('g', 'Граммы')], default='g', max_length=2, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Ingredient',
            field=models.ManyToManyField(to='api.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(to='api.teg', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_preparations',
            field=models.IntegerField(help_text='в минутах', verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='teg',
            name='slug',
            field=models.SlugField(help_text='Slug страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True),
        ),
    ]
