# Generated by Django 4.2.16 on 2024-11-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
