# Generated by Django 4.2.16 on 2024-11-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
