# Generated by Django 4.2.16 on 2024-11-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_basket_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='link',
        ),
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
