name: Основной рабочий процесс foodgram
on:
  push:
    branches:
      - main
jobs:
  backend_tests:
    name: Тестирование backend
    runs-on: ubuntu-latest
    steps:
      - name: Получения исходного кода
        uses: actions/checkout@v3
      - name: Установка пайтон
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip 
          pip install flake8==6.0.0
          pip install -r ./backend/requirements.txt 
      - name: Проверяем flake8
        run: python -m flake8 backend/
  push_to_dockerhub_backend:
    name: Отправка образа backend на DockerHub
    runs-on: ubuntu-latest
    needs: backend_tests
    steps:
      - name: Получение исходного кода из репозитория
        uses: actions/checkout@v3
      - name: Установка сборщика контейнеров Docker
        uses: docker/setup-buildx-action@v2
      - name: Авторизация на Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Одновременный билд и пуш образа в Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: kasyak999/foodgram-backend:latest
  push_to_dockerhub_frontend:
    name: Отправка образа frontend на DockerHub
    runs-on: ubuntu-latest
    needs: backend_tests
    steps:
      - name: Получение исходного кода из репозитория
        uses: actions/checkout@v3
      - name: Установка сборщика контейнеров Docker
        uses: docker/setup-buildx-action@v2
      - name: Авторизация на Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Одновременный билд и пуш образа в Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: kasyak999/foodgram-frontend:latest
  push_to_dockerhub_nginx:
    name: Отправка образа nginx на DockerHub
    runs-on: ubuntu-latest
    needs:
      - backend_tests
    steps:
      - name: Получение исходного кода из репозитория
        uses: actions/checkout@v3
      - name: Установка сборщика контейнеров Docker
        uses: docker/setup-buildx-action@v2
      - name: Авторизация на Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Одновременный билд и пуш образа в Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./nginx/
          push: true
          tags: kasyak999/foodgram-gateway:latest
  deploy:
    name: Загрузка на удаленный сервер
    runs-on: ubuntu-latest
    needs: 
      - push_to_dockerhub_backend
      - push_to_dockerhub_frontend
      - push_to_dockerhub_nginx
    steps:
    - name: Получение исходного кода из репозитория
      uses: actions/checkout@v3
    - name: Копируем docker-compose.production.yml на сервер
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "docker-compose.production.yml"
        target: "foodgram"
    - name: Выполнение удаленных команд ssh для развертывания
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd foodgram
          echo "Обновляем"
          sudo docker compose -f docker-compose.production.yml pull
          echo "готово"
          echo "Остановить compose"
          sudo docker compose -f docker-compose.production.yml down
          echo "готово"
          echo "Запуск compose в фоне"
          sudo docker compose -f docker-compose.production.yml up -d
          echo "готово"
          echo "Очищаем мусор в докерах"
          sudo docker system prune -af
  send_message:
    name: Отправка сообщения в телеграмм
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Деплой на kittygram999.zapto.org успешно выполнен!